app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(input_system = "Intensive vegetable production")
app$setInputs(input_system = "Pasture conversion")
app$setInputs(input_crop = "Barley_Spring")
app$setInputs(input_PlantingDate = "2018-10-25")
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(input_targetYield = "179")
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "Harvested_value"))
app$snapshot(list(output = "N_uptake_estimated"))
app$setInputs(N_inCrop_rows_selected = 1, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_row_last_clicked = 1, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_cell_clicked = c("1", "1", "0"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "N_inCrop"))
app$setInputs(N_inCrop_rows_selected = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_row_last_clicked = 2, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_cell_clicked = c("2", "1", "-40"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "N_inCrop"))
app$setInputs(N_inCrop_rows_selected = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_row_last_clicked = 3, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_cell_clicked = c("3", "1", "40(surplus)"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "N_inCrop"))
app$setInputs(input_nextsamplingDate = "2018-11-30")
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(`Sampling.Date` = "2018-11-30")
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(Qtest1 = 50)
app$setInputs(`N.calculated_rows_current` = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(`N.calculated_rows_all` = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(Qtest2 = 10)
app$setInputs(`N.calculated_rows_current` = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(`N.calculated_rows_all` = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(Qtest3 = 10)
app$setInputs(`N.calculated_rows_current` = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(`N.calculated_rows_all` = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_selected = 1, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_row_last_clicked = 1, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_cell_clicked = c("1", "1", "129"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "N_inCrop"))
app$setInputs(N_inCrop_rows_selected = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_row_last_clicked = 2, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_cell_clicked = c("2", "1", "171"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "N_inCrop"))
app$setInputs(N_inCrop_rows_selected = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_row_last_clicked = 3, allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_cell_clicked = c("3", "1", "-42(deficit)"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "N_inCrop"))
app$snapshot()
app$snapshot()
