app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(input_PlantingDate = "2020-03-01")
app$setInputs(`Sampling.Date` = "2020-03-26")
app$setInputs(input_nextsamplingDate = "2020-05-09")
app$setInputs(input_componentYield = "10")
app$setInputs(JumpToSoil = "click")
app$setInputs(samplingDepth = "0-15 cm")
app$setInputs(`Texture.1.1` = "Clay loam")
app$setInputs(`Moisture.1.1` = "Moist-Dry")
app$setInputs(`nextLayer.1.1` = "click")
app$setInputs(`Texture.1.2` = "Clay loam")
app$setInputs(`Moisture.1.2` = "Moist")
app$setInputs(JumpToReport = "click")
app$snapshot()
