app <- ShinyDriver$new("../")
app$snapshotInit("test_CropSection")

app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(input_crop = "Barley_Spring")
app$setInputs(input_targetYield = "90")
app$setInputs(N_require_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_require_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_current = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$setInputs(N_inCrop_rows_all = c(1, 2, 3), allowInputNoBinding_ = TRUE)
app$snapshot()
