---
title: "converExcelTo"
author: "Jian"
date: "5 September 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(DBI)
library(RSQLite)

sheets <- excel_sheets("C:/Data/QuickTestMassBalanceCalculator/QTMB Tool - V 2.1.xlsx")
sh <- grep("parameters| graphing|AMN input", sheets, value = T,ignore.case = T)
# l <- lapply(sh, function(x) read_excel("../QTMB Tool - V 2.1.xlsx", sheet = x))
path <- "../QTMB Tool - V 2.1.xlsx"
```
_Note_


crop relative sheets need to be read individually

# Soil

_Note_

1. what is the col after grey the col for? 
```{r soil}
soil <- read_excel(path, sheet =  sh[1]) %>% 
  select(-...9, -...11, -...12)
head(soil)
cols <- colnames(soil)
units <- regmatches(cols, gregexpr("\\(.+\\D", cols))
names(units) <- cols
units_df <- units %>% 
  enframe(name = "origin", value = "unit") %>% 
  unnest()


cols_new <- gsub("\\s", ".", gsub("\\s$","",gsub("\\(.+\\)", "", cols)))
names(cols_new) <- cols
cols_new_df <- cols_new %>% 
  enframe(name = "origin", value = "new") %>% 
  unnest()

meta_soil <- tibble(origin = cols) %>% 
  left_join(cols_new_df) %>% 
  left_join(units_df) 

colnames(soil) <- cols_new
# soil %>% 
#   ggplot(aes(Texture, Moisture.value)) +
#   geom_point() + 
#   coord_flip() +
#   facet_wrap( ~ Sampling.Depth, ncol = 1) +
#   theme_light() + 
#   theme(panel.grid.minor = element_blank(),
#         text = element_text(family = "sans"))
soil <- soil %>% 
  separate(Sampling.Depth, c("upper","lower"), remove = FALSE) %>% 
  # mutate(Sampling.Depth = gsub("\\d{1,2}-","", Sampling.Depth)) %>% 
  select(-Soil.Texture.INPUT,
         -Helper) %>% 
  mutate(upper = as.integer(upper),
         lower = as.integer(lower))
```


# Crop


```{r crop}
crop <- read_excel(path, sheet = sh[2],skip = 1) 
crop_info <- crop %>% 
  select(Crop = Crop...1, `Yield value`, Helper, `Harvested value`, `Helper 2`, `Seasonal N uptake (kg/ha)`, B, M, C, A)


cols <- colnames(crop_info)


units <-  regmatches(cols, gregexpr("\\(.+\\D", cols))

names(units) <- cols
units_df <- units %>% 
  enframe(name = "origin", value = "unit") %>% 
  unnest()


cols_new <- gsub("\\s", ".", gsub("\\s$","",gsub("\\(.+\\)", "", cols)))
names(cols_new) <- cols
cols_new_df <- cols_new %>% 
  enframe(name = "origin", value = "new") %>% 
  unnest()

meta_crop <- tibble(origin = cols) %>% 
  left_join(cols_new_df) %>% 
  left_join(units_df) 
colnames(crop_info) <- cols_new

crop_cleaned <- crop_info %>% 
  mutate(Yield.value = as.integer(Yield.value),
         Harvested.value = ifelse(is.na(Harvested.value), Yield.value, as.integer(Harvested.value)),
         Seasonal.N.uptake = round(as.numeric(Seasonal.N.uptake),digits = 0),
         B = as.numeric(B),
         M = as.numeric(M),
         C = as.numeric(C),
         A = as.numeric(A)) 
crop_para <- crop %>% 
  select(Crop = Crop...12, `Yield paramater`,`Harvested parameter`,Cultivar) %>% 
  filter(!is.na(Crop))
cols <- colnames(crop_para)
names(crop_para) <- cols
cols_new <- gsub("\\s", ".", gsub("\\s$","",gsub("\\(.+\\)", "", cols)))
names(cols_new) <- cols
meta_crop_para <- cols_new %>% 
  enframe(name = "origin", value = "new") %>% 
  unnest()
names(crop_para) <- cols_new


```

##### Revise the crop parameter values
```{r recode the harvested parameter}
crop_para <- crop_para %>% 
  mutate(Harvested.parameter = ifelse(is.na(Harvested.parameter),
                                      Yield.paramater, Harvested.parameter),
         Crop_name_display = gsub("(_)(Autumn|Summer|Spring|Winter)",
                                  " - \\2 planting", Crop),
         Crop_name_display = recode(Crop_name_display, 
                                    "Baby_Spinach" = "Baby Spinach",
                                    "Wheat - Autumn planting" = "Wheat - Autumn sown", 
                                    "Wheat - Spring planting" = "Wheat - Spring sown",
                                    "Barley - Autumn planting" = "Barley - Autumn sown",
                                    "Barley - Spring planting" = "Barley - Spring sown"))  
```

# Crop N


# MinN

# AMN

```{r amn}

notes <- read_excel(path, sh[5], range = "A2:A4", col_names = "Notes")
notes_AMN <- notes %>% 
  mutate(Notes = gsub("^.....", "", Notes),
         source = "AMN")
tab_AMN <- read_excel(path, sh[5], skip = 5) 

tab_AMN <- tab_AMN %>% 
  rename(AMN_default = `AMN (kg/ha)`,
         AMN_long = `AMN availability > 100`,
         AMN_intermedia = `AMN availability  40-100`,
         AMN_short = `AMN availability < 40`) %>% 
  gather(key = "DAP",value = "value", -System, -AMN_default) %>% 
  mutate(N_supply = AMN_default * value)

```

# write tables into sqlite3


```{r sql connection and write out}
con <- dbConnect(RSQLite::SQLite(),'../shinyapp/qtmb_data.sqlite3')
dbListTables(con)
dbWriteTable(con, "tab_AMN", tab_AMN, overwrite = TRUE)
dbWriteTable(con, "tab_crop.para", crop_para, overwrite = TRUE)
dbWriteTable(con, "tab_crop", crop_cleaned, overwrite = TRUE)
dbWriteTable(con, "tab_soil", soil, overwrite = TRUE)
# dbExecute(con," CREATE TABLE `tab_AMN` (
#   `System` TEXT NOT NULL,
#   `variable` int NOT NULL,
#   `value` int NOT NULL
# );
# ")
dbDisconnect(con)
```
